### ISSUE TITLE
Defaults are not set automatically

### ISSUE THREAD

**Issue by amberasaurus** [ellor1138/Lobot#1]
The wiki specifies that the necessary variables to get Lobot to work are defaulted to some values, but I had to manually set these variables (lobotProtectionIsEnabled, lobotProtectionKey, lobotProtectionAlgorythm) manually in app.cfm in order to get my application to load.

**Comment by ellor1138** [comment]
Unfortunately, the plugin is not compatible with the latest version of Wheels. Wheels 1.3.x changed the way plugins are loaded into the framework. I have not updated the plugin as I've found it was causing a lot of problems mainly with routes.

**Comment by amberasaurus** [comment]
My mistake! Should have posted to the group before attempting to use/log issues. Thanks again!

**Comment by ellor1138** [comment]
No problem. That's what Github is made for!

On 12 March 2015 at 14:35, Amber Cline notifications@github.com wrote:

> My mistake! Should have posted to the group before attempting to use/log
> issues. Thanks again!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ellor1138/Lobot/issues/1#issuecomment-78560098.

## 

[image: --]

Simon
[image: http://]about.me/ellor1138
http://about.me/ellor1138?promo=email_sig
